### ISSUE TITLE
Getting missing file from job returns 500 instead of 404

### ISSUE THREAD

**Issue by sverhoeven** [i-VRESSE/haddock3-webapp#142]
**Describe the bug**
When I have a completed job and try to access a file that does not exist I expected to get a 404 note found error, but I get a empty html page with 500 status code.

**To Reproduce**

1. Start dev server inside devcontainer
2. Submit any job
3. Goto a file that does exist
4. Change end of url so it does not exist

**Expected behavior**
Page with `Page not found` message.

**Additional context**

In the server log 

```
8:22:04 AM [vite] Internal server error: This stream has already been locked for exclusive reading by another reader
      at new ReadableStreamDefaultReader (/workspace/node_modules/web-streams-polyfill/dist/ponyfill.js:511:23)
      at AcquireReadableStreamDefaultReader (/workspace/node_modules/web-streams-polyfill/dist/ponyfill.js:472:16)
      at AcquireReadableStreamAsyncIterator (/workspace/node_modules/web-streams-polyfill/dist/ponyfill.js:866:22)
      at ReadableStream.values (/workspace/node_modules/web-streams-polyfill/dist/ponyfill.js:4181:20)
      at from (node:internal/streams/from:31:45)
      at Readable.from (node:internal/streams/readable:1727:10)
      at Object.toNodeRequest (/workspace/node_modules/@remix-run/dev/dist/vite/node-adapter.js:71:36)
      at nodeHandler (/workspace/node_modules/@remix-run/dev/dist/vite/plugin.js:845:35)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /workspace/node_modules/@remix-run/dev/dist/vite/plugin.js:847:15
```

**Comment by sverhoeven** [comment]
When run in production with for example the deploy/arq/docker-compose.yml it does return status code 404
